### ISSUE TITLE
Migrate away from deprecated gulp-util dependency

### ISSUE THREAD

**Issue by thephilgray** [Lanfei/gulp-file-assets#1]
I'm using this package in a project and noticed that one of its dependencies has been deprecated. According to [this post from Gulp](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5), `gulp-util` should be migrated as follows:

gutil.File => https://www.npmjs.com/package/vinyl
gutil.colors => https://www.npmjs.com/package/ansi-colors
gutil.log => https://www.npmjs.com/package/fancy-log
gutil.PluginError => https://www.npmjs.com/package/plugin-error

I can send a PR if you're interested.

Thanks!

**Comment by Lanfei** [comment]
Hi @thephilgray , thanks for the info!

Published [gulp-file-assets@3.0.0](https://www.npmjs.com/package/gulp-file-assets) to solve this issue :)
